apiVersion: trait.oam.vela/v1alpha1
kind: OamTrait
metadata:
  name: "backend"
  namespace: "default"
spec:
  name: "backend"
  replicas: 1
  image: "public.ecr.aws/m8u2y2m7/oam:backendv1"
  port: 8080
  max_replicas: 2
  cpu_target: 80
  expose_ingress: "no"
  