# permissions for end users to edit oamtraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: oamtrait-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: oamtrait-editor-role
rules:
- apiGroups:
  - trait.oam.vela
  resources:
  - oamtraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trait.oam.vela
  resources:
  - oamtraits/status
  verbs:
  - get
