---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - trait.oam.vela
  resources:
  - oamtraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trait.oam.vela
  resources:
  - oamtraits/finalizers
  verbs:
  - update
- apiGroups:
  - trait.oam.vela
  resources:
  - oamtraits/status
  verbs:
  - get
  - patch
  - update
