apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: eks-workshop-app
spec:
  components:
    - name: proddtl-backend
      type: microservice
      properties:
        name: proddtl-backend
        image: "public.ecr.aws/u2g6w7p2/eks-workshop-demo/catalog_detail:1.0"
        port: 3000
      traits:
      - type: autoscaler
    - name: prodcatalog-backend
      type: microservice
      properties:
        name: prodcatalog-backend
        image: "public.ecr.aws/u2g6w7p2/eks-workshop-demo/product_catalog:1.0"
        port: 5000
        env_name: AGG_APP_URL
        env_value: "http://proddtl-backend:3000/catalogDetail"
      traits:
      - type: autoscaler
    - name: prodcatalog-frontend
      type: microservice
      properties:
        name: prodcatalog-frontend
        image: "public.ecr.aws/u2g6w7p2/eks-workshop-demo/frontend_node:2.0"
        port: 9000
        env_name: BASE_URL
        env_value: "http://prodcatalog-backend:5000/products/"
      traits:
      - type: autoscaler
      - type: aws-alb-ingress
    
    
