apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app
spec:
  components:
    - name: proddetail
      type: my-comp
      properties:
        name: proddetail
        image: "public.ecr.aws/u2g6w7p2/eks-workshop-demo/catalog_detail:1.0"
        port: 3000
        env_name: "APPLICATION_URL"
        env_value: "http://prodcatalog:5000/prodCatalog"
      traits:
      - type: autoscaler
        properties:
          min: 1
    - name: prodcatalog
      type: my-comp
      properties:
        name: prodcatalog
        image: "public.ecr.aws/u2g6w7p2/eks-workshop-demo/product_catalog:1.0"
        port: 5000
        env_name: AGG_APP_URL
        env_value: " http://proddetail:3000/catalogDetail"
      traits:
      - type: autoscaler
        properties:
          min: 1
    - name: frontend
      type: my-comp
      properties:
        name: frontend
        image: "public.ecr.aws/u2g6w7p2/eks-workshop-demo/frontend_node:2.0"
        port: 9000
        env_name: BASE_URL
        env_value: "http://prodcatalog:5000/products/"
      traits:
      - type: autoscaler
        properties:
          min: 1      
      - type: ingtrait
    
    
