apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: my-comp
  annotations:
    definition.oam.dev/description: "It's my component"
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        output: {
            apiVersion: "apps/v1"
            kind:       "Deployment"
            spec: {
                selector: matchLabels: {
                    "app": context.name
                }
                template: {
                    metadata: labels: {
                        "app": context.name
                    }
                    spec: {
                        containers: [{
                            name:  context.name
                            image: parameter.image
                            if parameter["cmd"] != _|_ {
                                command: parameter.cmd
                            }
                        }]
                    }
                }
            }
        }
        parameter: {
            image: string
            cmd?: [...string]
            port:     *3000 | int
        }
        outputs: "service": {
        	apiVersion: "v1"
        	kind:       "Service"
        	metadata: name:  context.name
        	spec: {
        		type: "ClusterIP"
        		selector: app:  context.name
        		ports: [{
        			name:       "http"
        			port:       parameter.port
        			protocol:   "TCP"
        		}]}}