apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: backend
spec:
  components:
    - name: backend
      type: webservice
      properties:
        image: "public.ecr.aws/m8u2y2m7/oam:frontend"
        ports:
          - port: 8080
            expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
