apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: frontend
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: "public.ecr.aws/m8u2y2m7/oam:frontendv1"
        ports:
          - port: 80
            expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
