apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: frontend
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: "public.ecr.aws/u2g6w7p2/eks-workshop-demo/frontend_node:2.0"
        ports:
          - port: 9000
            expose: true
        exposeType: NodePort
      traits:
        - type: gateway
          properties:
            domain: frontend
            http:
              "/": 9000
        - type: scaler
          properties:
            replicas: 1
