apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: front-end
spec:
  components:
    - name: front-end
      type: webservice
      properties:
        image: nginx
        port: 80
