apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: front-end-app
spec:
  components:
    - name: front-end-po
      type: webservice
      properties:
        image: public.ecr.aws/u2g6w7p2/eks-workshop-demo/frontend_node:2.0
        port: 80
      traits:
        - type: ingress
          properties:
            rules:
            - http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: test
                      port:
                        number: 80
